
name: CI

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
        with:
          node-version: 14.16.1
      - run: npm install
      - run: npm ci
      - run: npm run build

    
